import Observation
import SwiftUI

// MARK: - ViewModelBindings

/// A model-owned namespace of SwiftUI bindings generated by `@ViewModel`.
///
/// Annotated fields synchronously dispatch their `@StateBinding` action. Other
/// stored fields commit directly through `updateState`. Copies share one stable
/// binding root, which retains State without retaining its ViewModel.
@MainActor
@dynamicMemberLookup
public struct ViewModelBindings<Model: ViewModel> {
  /// Creates the binding root. Generated models retain this value lazily once.
  /// Application code should use `viewModel.bindings`, not recreate it in a view.
  public init(_ model: Model) {
    _visorStorage = _ViewModelBindingStorage(model)
  }

  public subscript<Value>(
    dynamicMember selection: KeyPath<Model._VISORBindingSelectors, _ViewModelBinding<Model, Value>>
  ) -> Binding<Value> {
    Bindable(_visorStorage)[selection]
  }

  let _visorStorage: _ViewModelBindingStorage<Model>
}

// MARK: - _ViewModelBinding

/// Typed field metadata used by generated model binding namespaces.
/// Public only because macro expansions are compiled in the consuming module.
@MainActor
public struct _ViewModelBinding<Model: ViewModel, Value> {

  // MARK: Lifecycle

  /// Describes a State getter and its synchronous model-owned write operation.
  public init(
    for _: Model.Type,
    keyPath: KeyPath<Model.State, Value>,
    write: @escaping @MainActor (Model, Value) -> Void,
  ) {
    self.keyPath = keyPath
    writeValue = write
  }

  // MARK: Fileprivate

  fileprivate func read(from state: Model.State) -> Value {
    state[keyPath: keyPath]
  }

  fileprivate func write(_ value: Value, to model: Model) {
    writeValue(model, value)
  }

  // MARK: Private

  private let keyPath: KeyPath<Model.State, Value>
  private let writeValue: @MainActor (Model, Value) -> Void
}

// MARK: - _ViewModelBindingStorage

/// The stable reference root of key-path-backed bindings. Its computed reads
/// track the authored State getter, so no additional observation registrar is
/// needed here. A binding can outlive the model: reads survive; writes do nothing.
@MainActor
final class _ViewModelBindingStorage<Model: ViewModel>: Observable {

  // MARK: Lifecycle

  init(_ model: Model) {
    state = model.state
    owner = model
  }

  // MARK: Internal

  subscript<Value>(
    _ selection: KeyPath<Model._VISORBindingSelectors, _ViewModelBinding<Model, Value>>
  ) -> Value {
    get {
      Model._visorBindingSelectors[keyPath: selection].read(from: state)
    }
    set {
      guard let owner else { return }
      Model._visorBindingSelectors[keyPath: selection].write(newValue, to: owner)
    }
  }

  // MARK: Private

  private let state: Model.State
  private weak var owner: Model?
}
