import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros

// MARK: - StateBindingMacro

/// Marker for synchronous binding action routes generated by `@ViewModel`.
public struct StateBindingMacro: PeerMacro {
  public static func expansion(
    of _: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext,
  ) throws -> [DeclSyntax] {
    let scopes = context.lexicalContext
    guard
      declaration.is(EnumCaseDeclSyntax.self),
      let action = scopes.first?.as(EnumDeclSyntax.self),
      action.name.text == "Action",
      scopes.dropFirst().first?.as(ClassDeclSyntax.self)?
        .attributes.visorContains(named: "ViewModel") == true
    else {
      context.diagnose(Diagnostic(node: Syntax(declaration), message: StateBindingDiagnostic.placement))
      return []
    }
    return []
  }
}
